name: Food Crawl Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "35 3 * * *"   # 한국시간 12:35 (UTC 03:35)

jobs:
  run-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests pillow selenium webdriver-manager easyocr

      - name: Install system packages (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run food crawl.py
        env:
          FLOW_URL: ${{ secrets.FLOW_URL }}   # ✅ GitHub Secrets에 Flow API Endpoint 저장
        run: python "food crawl.py"
