name: Food OCR Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "35 3 * * *"   # 한국시간 12:35 실행 (UTC+0 기준 03:35)

jobs:
  run-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests pillow pytesseract selenium

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-kor

      - name: Run OCR crawler
        env:
          FLOW_URL: ${{ secrets.FLOW_URL }}   # ✅ GitHub Secret에서 FLOW_URL 가져옴
        run: python "food crawl.py"
