name: Food Crawl AI Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "35 3 * * *"   # 한국시간 12:35 실행 (UTC 기준 03:35)

jobs:
  run-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests pillow selenium webdriver-manager huggingface_hub

      - name: Run food crawl.py
        env:
          FLOW_URL: ${{ secrets.FLOW_URL }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # Hugging Face 토큰 (무료 계정 생성 후 Settings에서 발급)
        run: python "food crawl.py"
