name: Food Crawl Bot   # ✅ Actions 탭에 보이는 이름

on:
  workflow_dispatch:   # 수동 실행
  schedule:
    - cron: "35 3 * * *"   # 한국시간 12:35 (UTC 03:35)

jobs:
  run-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests pillow pytesseract selenium webdriver-manager

      - name: Install system packages (Tesseract & Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-kor \
            google-chrome-stable

      - name: Run food crawl.py
        env:
          FLOW_URL: ${{ secrets.FLOW_URL }}   # ✅ GitHub Secrets에 등록한 Flow API Endpoint
        run: python "food crawl.py"
