name: Teams Notify Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "45 3 * * *"   # 한국시간 12:35 실행

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 selenium

      - name: Run crawler
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python "food crawl.py"
